#!/usr/bin/env python3
"""
Qt6 Setup and Configuration for PhiGEN Project
Connects the project to MSYS2 Qt6 tools and libraries.
"""

import os
import sys
import subprocess
from pathlib import Path

# MSYS2 Qt6 paths
MSYS2_UCRT64_BIN = Path(r'E:\Utilities\MINGSYS2\ucrt64\bin')
MSYS2_UCRT64_LIB = Path(r'E:\Utilities\MINGSYS2\ucrt64\lib')

# Qt6 tools available
QT_TOOLS = {
    'designer': 'designer-qt6.exe',
    'assistant': 'assistant-qt6.exe',
    'linguist': 'linguist-qt6.exe',
    'qmake': 'qmake-qt6.exe',
    'uic': 'uic-qt6.exe',
}

# Qt6 DLLs
QT_DLLS = [
    'Qt6Core.dll',
    'Qt6Gui.dll',
    'Qt6Widgets.dll',
    'Qt6Network.dll',
    'Qt6OpenGL.dll',
    'Qt6OpenGLWidgets.dll',
    'Qt6Sql.dll',
    'Qt6Test.dll',
    'Qt6PrintSupport.dll',
]


def check_qt_installation():
    """Check if Qt6 tools are available in MSYS2."""
    print("Checking Qt6 installation in MSYS2...")
    print(f"MSYS2 bin path: {MSYS2_UCRT64_BIN}\n")

    available = []
    missing = []

    # Check tools
    print("Qt6 Tools:")
    for name, exe in QT_TOOLS.items():
        path = MSYS2_UCRT64_BIN / exe
        if path.exists():
            available.append(exe)
            print(f"  [OK] {name:15s} - {exe}")
        else:
            missing.append(exe)
            print(f"  [  ] {name:15s} - {exe} (NOT FOUND)")

    # Check DLLs
    print("\nQt6 DLLs:")
    dll_count = 0
    for dll in QT_DLLS:
        path = MSYS2_UCRT64_BIN / dll
        if path.exists():
            dll_count += 1
            print(f"  [OK] {dll}")

    print(f"\nSummary:")
    print(f"  Tools: {len(available)}/{len(QT_TOOLS)} available")
    print(f"  DLLs:  {dll_count}/{len(QT_DLLS)} available")

    return len(available) > 0


def check_python_qt_bindings():
    """Check if PyQt6 or PySide6 is installed."""
    print("\n" + "="*70)
    print("Checking Python Qt bindings...")

    bindings = []

    try:
        import PyQt6
        version = PyQt6.QtCore.PYQT_VERSION_STR
        bindings.append(('PyQt6', version))
        print(f"  [OK] PyQt6 {version} installed")
    except ImportError:
        print(f"  [  ] PyQt6 not installed")

    try:
        import PySide6
        version = PySide6.__version__
        bindings.append(('PySide6', version))
        print(f"  [OK] PySide6 {version} installed")
    except ImportError:
        print(f"  [  ] PySide6 not installed")

    return bindings


def install_pyqt6():
    """Install PyQt6 in the current Python environment."""
    print("\n" + "="*70)
    print("Installing PyQt6...")

    cmd = [sys.executable, '-m', 'pip', 'install', 'PyQt6']

    result = subprocess.run(cmd, capture_output=True, text=True)

    if result.returncode == 0:
        print("[OK] PyQt6 installed successfully!")
        return True
    else:
        print(f"[FAIL] Installation failed: {result.stderr}")
        return False


def create_qt_env_script():
    """Create environment setup script for Qt tools."""
    script_content = f"""@echo off
REM Qt6 Environment Setup for PhiGEN
REM Adds MSYS2 Qt6 tools to PATH

set MSYS2_UCRT64_BIN={MSYS2_UCRT64_BIN}
set PATH=%MSYS2_UCRT64_BIN%;%PATH%

echo Qt6 environment configured!
echo.
echo Available Qt tools:
echo   designer-qt6    - Qt Designer (UI editor)
echo   assistant-qt6   - Qt Assistant (documentation)
echo   linguist-qt6    - Qt Linguist (translations)
echo   qmake-qt6       - Qt build tool
echo.
echo Usage:
echo   designer-qt6        Launch Qt Designer
echo   qmake-qt6 --version Show Qt version
echo.

cmd /k
"""

    script_path = Path(__file__).parent / 'qt_env.bat'
    script_path.write_text(script_content)

    print(f"\n[OK] Created environment script: {script_path.name}")
    print(f"     Run this to access Qt tools from command line")

    return script_path


def create_qt_config():
    """Create Qt configuration module for Python."""
    config_content = f'''"""
Qt6 Configuration for PhiGEN
Auto-generated by setup_qt.py
"""

import os
import sys
from pathlib import Path

# MSYS2 Qt6 paths
MSYS2_UCRT64_BIN = Path(r'{MSYS2_UCRT64_BIN}')
MSYS2_UCRT64_LIB = Path(r'{MSYS2_UCRT64_LIB}')

# Qt6 tools
QT_DESIGNER = MSYS2_UCRT64_BIN / 'designer-qt6.exe'
QT_ASSISTANT = MSYS2_UCRT64_BIN / 'assistant-qt6.exe'
QT_LINGUIST = MSYS2_UCRT64_BIN / 'linguist-qt6.exe'
QT_QMAKE = MSYS2_UCRT64_BIN / 'qmake-qt6.exe'


def setup_qt_environment():
    """Add Qt6 DLLs to PATH and DLL search path."""
    # Add to PATH
    bin_str = str(MSYS2_UCRT64_BIN)
    if bin_str not in os.environ.get('PATH', ''):
        os.environ['PATH'] = bin_str + os.pathsep + os.environ.get('PATH', '')

    # Add DLL directory (Windows 10+)
    if hasattr(os, 'add_dll_directory'):
        os.add_dll_directory(bin_str)

    return True


def launch_designer():
    """Launch Qt Designer."""
    import subprocess
    if QT_DESIGNER.exists():
        subprocess.Popen([str(QT_DESIGNER)])
        return True
    return False


def launch_assistant():
    """Launch Qt Assistant."""
    import subprocess
    if QT_ASSISTANT.exists():
        subprocess.Popen([str(QT_ASSISTANT)])
        return True
    return False


# Auto-setup on import
setup_qt_environment()
'''

    config_path = Path(__file__).parent / 'qt_config.py'
    config_path.write_text(config_content)

    print(f"[OK] Created Qt configuration: {config_path.name}")
    print(f"     Import this in your Python scripts: from qt_config import *")

    return config_path


def main():
    print("="*70)
    print("Qt6 Setup for PhiGEN Project")
    print("="*70)

    # Step 1: Check Qt installation
    if not check_qt_installation():
        print("\n[WARNING] Qt6 not found in MSYS2!")
        print("  Please install Qt6 in MSYS2 using:")
        print("  pacman -S mingw-w64-ucrt-x86_64-qt6")
        return

    # Step 2: Check Python bindings
    bindings = check_python_qt_bindings()

    # Step 3: Offer to install PyQt6 if not present
    if not bindings:
        print("\nNo Python Qt bindings found.")
        print("Installing PyQt6 automatically...")
        install_pyqt6()

    # Step 4: Create helper scripts
    print("\n" + "="*70)
    print("Creating helper scripts...")

    create_qt_env_script()
    create_qt_config()

    # Summary
    print("\n" + "="*70)
    print("Setup Complete!")
    print("="*70)
    print("\nHow to use Qt6 in your project:")
    print("\n1. In Python scripts:")
    print("   from qt_config import setup_qt_environment, launch_designer")
    print("   setup_qt_environment()  # Add Qt DLLs to PATH")
    print("   launch_designer()        # Launch Qt Designer")
    print("\n2. In command line:")
    print("   qt_env.bat              # Opens shell with Qt tools")
    print("   designer-qt6            # Launch Qt Designer")
    print("\n3. With PyQt6:")
    print("   from PyQt6.QtWidgets import QApplication, QWidget")
    print("   # Qt DLLs automatically available via qt_config")


if __name__ == '__main__':
    main()
