"""
Qt6 Configuration for PhiGEN
Auto-generated by setup_qt.py
"""

import os
import sys
from pathlib import Path

# MSYS2 Qt6 paths
MSYS2_UCRT64_BIN = Path(r'E:\Utilities\MINGSYS2\ucrt64\bin')
MSYS2_UCRT64_LIB = Path(r'E:\Utilities\MINGSYS2\ucrt64\lib')

# Qt6 tools
QT_DESIGNER = MSYS2_UCRT64_BIN / 'designer-qt6.exe'
QT_ASSISTANT = MSYS2_UCRT64_BIN / 'assistant-qt6.exe'
QT_LINGUIST = MSYS2_UCRT64_BIN / 'linguist-qt6.exe'
QT_QMAKE = MSYS2_UCRT64_BIN / 'qmake-qt6.exe'


def setup_qt_environment():
    """Add Qt6 DLLs to PATH and DLL search path."""
    # Add to PATH
    bin_str = str(MSYS2_UCRT64_BIN)
    if bin_str not in os.environ.get('PATH', ''):
        os.environ['PATH'] = bin_str + os.pathsep + os.environ.get('PATH', '')

    # Add DLL directory (Windows 10+)
    if hasattr(os, 'add_dll_directory'):
        os.add_dll_directory(bin_str)

    return True


def launch_designer():
    """Launch Qt Designer."""
    import subprocess
    if QT_DESIGNER.exists():
        subprocess.Popen([str(QT_DESIGNER)])
        return True
    return False


def launch_assistant():
    """Launch Qt Assistant."""
    import subprocess
    if QT_ASSISTANT.exists():
        subprocess.Popen([str(QT_ASSISTANT)])
        return True
    return False


# Auto-setup on import
setup_qt_environment()
